name: CI

on:
  push:
  pull_request:
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  ubuntu_test:
    strategy:
      matrix:
        runs-on: [ubuntu-20.04, ubuntu-22.04]
    runs-on: ${{ matrix.runs-on }}
    steps:
    - uses: actions/checkout@v3
    - name: apt
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake python3-pip
    - name: pip
      run: |
        python3 -m pip install --user git+https://github.com/johnwason/drekar-launch-process.git
        python3 -m pip install --user git+https://github.com/johnwason/drekar-launch.git
    - name: configure
      run: |
        mkdir build
        cd build
        cmake -DBUILD_TESTING=ON .. 
    - name: build
      run: |
        cd build
        cmake --build .
    - name: test
      run: |
        python3 -m drekar_launch --config=test/drekar-launch/drekar-launch.yaml
  windows_test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: pip
      run: |
        python -m pip install --user git+https://github.com/johnwason/drekar-launch-process.git
        python -m pip install --user git+https://github.com/johnwason/drekar-launch.git
    - name: configure
      run: |
        mkdir build
        cd build
        cmake -G Ninja -DBUILD_TESTING=ON .. 
    - name: build
      run: |
        cd build
        cmake --build .
    - name: test
      run: |
        python -m drekar_launch --config=test/drekar-launch/drekar-launch.yaml
   